package recipe

import "github.com/pietervanleuven/rehost/internal/detect"

// genericExcludes never belong in a migration regardless of framework.
//
// .ssh and .rehost matter when a site root turns out to be the account home
// — some shared hosts serve ~ directly, and the docroot-candidate scan
// reaches it. Without them the sync would carry the account's private keys
// to the destination, and would overwrite the destination's own .rehost
// state with the source's: that history is what marks a docroot as
// rehost-created (the rerun exemption) and what unlock recovers from.
// Excludes prune an exact root-relative path, so these only ever apply at
// the site root, never to a nested directory that happens to share a name.
var genericExcludes = []string{".git", "node_modules", ".ssh", ".rehost"}

// ExcludeSuggestionsFor returns root-relative directories that are safe to
// leave behind when they exist: caches and backup dumps the framework (or
// its ecosystem plugins) regenerates or re-creates. The inventory measures
// which of them actually exist and what they weigh.
func ExcludeSuggestionsFor(in detect.Install) []string {
	switch in.Framework {
	case "wordpress":
		return append([]string{
			// .maintenance is the runtime maintenance sentinel rehost writes on
			// the source during the migration window; excluding it keeps the
			// delta pass from carrying it onto the destination, where nothing
			// clears it and the migrated site would serve a permanent 503.
			".maintenance",
			"wp-content/cache",
			"wp-content/uploads/cache",
			"wp-content/w3tc-cache",
			"wp-content/updraft",
			"wp-content/ai1wm-backups",
			"wp-content/backups-dup-pro",
		}, genericExcludes...)
	case "drupal":
		return append([]string{
			// css/js/php are compiled artifacts, styles are regenerable
			// image derivatives — Drupal rebuilds all of them.
			"sites/default/files/css",
			"sites/default/files/js",
			"sites/default/files/php",
			"sites/default/files/styles",
		}, genericExcludes...)
	case "joomla":
		return append([]string{
			// Both cache trees plus tmp are regenerated by Joomla itself.
			"cache",
			"administrator/cache",
			"tmp",
		}, genericExcludes...)
	case "prestashop":
		return append([]string{
			// 1.7/8 Symfony cache, 1.6 Smarty cache, and image-resize temp.
			"var/cache",
			"cache/smarty/cache",
			"cache/smarty/compile",
			"img/tmp",
		}, genericExcludes...)
	case "craft":
		return append([]string{
			// Craft regenerates runtime caches and resource bundles; local
			// backups have no business traveling to the new host.
			"storage/runtime",
			"storage/logs",
			"storage/backups",
			"web/cpresources",
		}, genericExcludes...)
	case "laravel":
		return append([]string{
			// The file cache store re-creates its tree on write and Monolog
			// creates the log directory. Compiled views, sessions and
			// bootstrap/cache must travel — Laravel does not recreate those
			// directories itself.
			"storage/framework/cache",
			"storage/logs",
		}, genericExcludes...)
	default:
		return genericExcludes
	}
}
